# use new container-based infrastructure
sudo: false

language: python

cache:
  pip: true
  directories:
    - .tox

install: pip install tox

env:
  - TOX_ENV=py2
  - TOX_ENV=py3
  - TOX_ENV=pypy

script:
  - tox -e $TOX_ENV
